## Atuin configuration

## If enabled, upon hitting enter Atuin will immediately execute the command.
enter_accept = true

[keys]
# Disable up arrow binding (we use --disable-up-arrow in atuin init instead)
up_arrow = false

[sync]
# Enable sync v2
records = true
